### ISSUE TITLE
Create CSS for edit-page

### ISSUE THREAD

**Issue by bregySilvan** [bregySilvan/Rasmus#17]
## Description
Currently I am working on ```EditBoardComponent``` => #5 . That component provides a page for displaying all available ```Advertisements```. This page need's also some creative and nice looking CSS design.

## todo
- [ ] Look at the spec and consult me if anything is unclear
- [ ] plan a basic design for given spec
- [ ] implement basic design
- All CSS for ```EditBoardsComponent``` should be added in ```client/src/app/components/advertisements.component.css``` file. 
## Spec
![image](https://user-images.githubusercontent.com/31403441/38783895-53525800-4109-11e8-8cdf-b4ffbfb8441e.png)
