### ISSUE TITLE
create basic css

### ISSUE THREAD

**Issue by bregySilvan** [bregySilvan/Rasmus#7]
## Description
I created some sort of a spec in #5 and implemented a basic client. 
The client can be runned in ```src/client``` folder using ```npm install``` and afterwards ``` npm start```.
Please make sure to have ```ts-node``` and ```typescript``` installed.

## toDo
- [ ] Please investigate for finding a CSS framework before writing everything by hand. Think about responsive design. In general the CSS should be made for Computer usage. Mobile will be made in future maybe.
- [ ] create default css for site. Probably you can't do lots of stuff here since there isn't done much from the client. 
- [ ] create css for login (spec is here #5)
- [ ] create css for edit Page 
- [ ] create css for main page. If you want you can also create a design for the mainpage.

## Info
Generally I am writing all my thoughts into #5 OR #1.
